### ISSUE TITLE
pip installation fails with ImportError: No module named 'cached_property'

### ISSUE THREAD

**Issue by BillBrower** [benediktschmitt/py-jsonapi#1]
```
(truesouth) desktop-u1n4oq8:truesouth brower$ pip3 install py-jsonapi
Collecting py-jsonapi
  Using cached py-jsonapi-0.3.1b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/setup.py", line 29, in <module>
        import jsonapi
      File "/private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/jsonapi/__init__.py", line 26, in <module>
        from . import base
      File "/private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/jsonapi/base/__init__.py", line 47, in <module>
        from . import handler
      File "/private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/jsonapi/base/handler/__init__.py", line 37, in <module>
        from .base import BaseHandler
      File "/private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/jsonapi/base/handler/base.py", line 32, in <module>
        from ..errors import MethodNotAllowed
      File "/private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/jsonapi/base/errors.py", line 37, in <module>
        from cached_property import cached_property
    ImportError: No module named 'cached_property'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/27/5vh9fhrj79sflj1n241x_vb00000gn/T/pip-build-uhbyateo/py-jsonapi/
```

**Comment by paridin** [comment]
You have installed [cached_property ](https://github.com/pydanny/cached-property)?

Maybe it will be included in the readme.

Dependencies:
cached_property 
```
pip install cached_property
```

**Comment by BillBrower** [comment]
@paridin I think the issue is the package name. It should be cached-property rather than cached_property.
