### ISSUE TITLE
Unable to install via pip due to SyntaxError

### ISSUE THREAD

**Issue by AlmightyOatmeal** [benediktschmitt/py-jsonapi#3]
Using Python 2.7.10, I'm not able to install py-jsonapi via pip:

```
╭─jamie@BeefCurtainMoses  ~
╰─$ sudo -H pip install py-jsonapi
Collecting py-jsonapi
  Downloading py-jsonapi-0.3.1b0.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 1.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-uJ_Iyr/py-jsonapi/setup.py", line 29, in <module>
        import jsonapi
      File "jsonapi/__init__.py", line 26, in <module>
        from . import base
      File "jsonapi/base/__init__.py", line 47, in <module>
        from . import handler
      File "jsonapi/base/handler/__init__.py", line 37, in <module>
        from .base import BaseHandler
      File "jsonapi/base/handler/base.py", line 31, in <module>
        from ..response import Response
      File "jsonapi/base/response.py", line 71
        def print(self):
                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-uJ_Iyr/py-jsonapi/
```

**Comment by AlmightyOatmeal** [comment]
Never mind, I stumbled upon this line:

* This library implements the http://jsonapi.org specification in Python 3.

Which it would have been helpful to have as part of a project description, conveyed on github, something other than needing to try to dig around for it.
